name: sam_jas_academy
description: "A professional Hair and Makeup Academy app with a premium Espresso theme."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- Network & SMS Logic ---
  http: ^1.6.0  # Added for your Windows Server .dll connection
  intl_phone_field: ^3.1.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  in_app_review: ^2.0.9
  flutter_pdfview: ^1.3.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  dio: ^5.4.0
  loading_animation_widget: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  email_otp: ^3.1.0 
  csv: ^6.0.0  
  share_plus: ^10.1.0
  excel: ^4.0.0
  file_picker: ^8.0.0  
  
  

  # --- Firebase Suite ---
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  
  # --- UI & Utilities ---
  flutter_native_splash: ^2.4.0
  percent_indicator: ^4.2.3
  razorpay_flutter: ^1.3.5
  image_picker: any
  google_fonts: ^8.0.1
  cupertino_icons: ^1.0.6
  
  
  # --- Video & Media ---
  youtube_player_flutter: ^9.1.1
  video_player: ^2.8.1
  chewie: ^1.7.1
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_android_video: ^1.1.3
  
  # --- Documents & System ---
  pdf: ^3.10.8
  printing: ^5.11.1
  device_info_plus: ^10.1.0
  visibility_detector: ^0.4.0+2
  saver_gallery: ^4.1.0
  gal: ^2.3.2
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^17.0.1
  timezone: ^0.9.4
  googleapis_auth: ^2.0.0
  webview_flutter: ^4.4.2  # Add this line here
  webview_flutter_android: ^4.10.11
  screen_protector: ^1.5.1
  showcaseview: ^3.0.0  # Or latest version
  shared_preferences: ^2.2.2
  pinput: ^4.0.0
  smart_auth: ^2.0.0 # Helps with the SMS User Consent API
  country_picker: ^2.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # --- ASSETS SECTION ---
  assets:
    - assets/images/slide1_new.png
    - assets/images/slide2.png
    - assets/images/slide3.png
    - assets/images/slide4.png
    - assets/images/logo-final-1.png
    - assets/service-account.json
  # --- FONTS SECTION ---
  fonts:
    - family: TrajanProCustom
      fonts:
        - asset: assets/fonts/TrajanPro-Regular.ttf

# Native Splash Configuration (Top Level)
flutter_native_splash:
  color: "#FFFDF1"
  image: "assets/images/logo-final-1.png"
  android_12:
    image: "assets/images/logo-final-1.png"
    icon_background_color: "#FFFDF1"
  fullscreen: true

# Launcher Icons Configuration (Top Level - No Indentation)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-final-1.png"
  adaptive_icon_background: "#0F0F0F"
  adaptive_icon_foreground: "assets/images/logo-final-1.png"